// GENERATED by tools/generate.js
import { Container } from "inversify";
import { TYPES } from "./types";

import { DiscordBot } from "./discord";

const container = new Container();

container.bind<DiscordBot>(TYPES.DiscordBot).to(DiscordBot);

export { container };
