// GENERATED by tools/generate.js
import "reflect-metadata";
import { Container } from "inversify";
import { TYPES } from "./types";

import { DiscordBot } from "./chatbots/discord/DiscordBot";
import { Client } from "discord.js";
import { TokenService } from "./credentials/TokenService";

import { DISCORD_INTENTS } from "./chatbots/discord/DiscordBot";

const container = new Container();

container.bind<DiscordBot>(TYPES.DiscordBot).to(DiscordBot);
container.bind<string>(TYPES.TokensFile)
	.toConstantValue("tokens.yml");
container.bind<Client>(TYPES.Client)
	.toConstantValue(new Client({ intents: DISCORD_INTENTS }));
container.bind<TokenService>(TYPES.TokenService).to(TokenService);

export { container };
