// GENERATED by tools/generate.js
export const TYPES = {
    DiscordBot: Symbol('DiscordBot'),
    TokensFile: Symbol('TokensFile'),
    Client: Symbol('Client'),
    TokenService: Symbol('TokenService'),
};
